# Generated by Django 4.2.11 on 2025-09-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_alter_note_options_alter_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
